version: '3.9'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=sachin
      - DB_NAME=notesdb
    depends_on:
      - db
    networks:
      - notes-network

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notesdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - notes-network

volumes:
  mysql_data:

networks:
  notes-network:
